version: '3.8'

services:
  warp:
    image: caomingjun/warp:latest
    container_name: chat2api-warp
    restart: always
    ports:
      - "1080:1080"
    environment:
      - WARP_SLEEP=2
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - warp_data:/var/lib/cloudflare-warp

  chat2api:
    image: lanqian528/chat2api:latest
    container_name: chat2api
    restart: always
    ports:
      - "5005:5005"
    environment:
      - API_PREFIX=
      - AUTHORIZATION=YOUR_API_KEY
      - PROXY_URL=socks5://warp:1080
      - HISTORY_DISABLED=true
      - ENABLE_GATEWAY=false
      - SCHEDULED_REFRESH=true
      - RANDOM_TOKEN=true
      - RETRY_TIMES=3
    depends_on:
      - warp
    volumes:
      - chat2api_data:/app/data

volumes:
  warp_data:
  chat2api_data:
